/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-01-30 08:18:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.qaBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.semiproject.member.model.vo.Member;

public final class QnA_005fMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/qaBoard/../common/footer.jsp", Long.valueOf(1579838816000L));
    _jspx_dependants.put("/WEB-INF/views/qaBoard/../common/sidebar.jsp", Long.valueOf(1580371987840L));
    _jspx_dependants.put("/WEB-INF/views/qaBoard/../common/header.jsp", Long.valueOf(1580057426000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.semiproject.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>미씽펫 - QnA 게시판</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\" id=\"row\">\r\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("\r\n");

	String msg = (String)session.getAttribute("msg");
	Member loginMember = (Member)session.getAttribute("loginMember");
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<script>\r\n");
      out.write("\t\t// 로그인 실패 메세지 출력 후 session에 남아있는 \"msg\" 속성 제거 \r\n");
      out.write("\t\t");
 if(msg != null){ 
      out.write("\r\n");
      out.write("\t\t\talert(\"");
      out.print( msg );
      out.write("\");\r\n");
      out.write("\t\t");
	session.removeAttribute("msg");
		 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("<div class=\"d-md-block bg-white sidebar\" id=\"sidebarAll\" style=\"z-index: 1100;\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"sidebar-sticky\" id=\"sidebarAll\">\r\n");
      out.write("\r\n");
      out.write("          <table class=\"table-responsive\">\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav flex-column\">\r\n");
      out.write("              <li class=\"align-items-center text-center\">\r\n");
      out.write("                <a id=\"logo\" href=\"index.jsp\">\r\n");
      out.write("                  <img src=\"");
      out.print( request.getContextPath() );
      out.write("/img/logo7.png\" width=150px>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\t\t\t");
 if(loginMember == null){ 
      out.write("\r\n");
      out.write("              <li class=\"nav-item align-items-center\">\r\n");
      out.write("              <a href=\"member/loginPage\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-primary btn-sm px-5 mt-5 p-3\" id=\"loginBtn\">로그인</button>\r\n");
      out.write("              </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("              \t<div class=\"justif-content-end align-items-center text-center\">\r\n");
      out.write("\t\t\t\t");
      out.print( loginMember.getMemberName() );
      out.write("님 환영합니다. \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a href=\"member/logout\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-secondary btn-sm px-3 mt-5 p-2\" id=\"loginBtn\">로그아웃</button>\r\n");
      out.write("              </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              ");
 } 
      out.write("\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"nav-item mt-5\">\r\n");
      out.write("                <p>&nbsp;</p>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item mt-3\">\r\n");
      out.write("                <p>&nbsp;</p>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item mb-1\">\r\n");
      out.write("                <a class=\"nav-link active text-center mt-4 mb-1\" href=\"#\">\r\n");
      out.write("                  찾아주세요\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item mb-1\">\r\n");
      out.write("                <a class=\"nav-link  text-center\" href=\"#\">\r\n");
      out.write("                  봤어요\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item mb-1\">\r\n");
      out.write("                <a class=\"nav-link  text-center\" href=\"#\">\r\n");
      out.write("                  입양했어요\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item mb-1\">\r\n");
      out.write("                <a class=\"nav-link  text-center\" href=\"#\">\r\n");
      out.write("                  만남 그 후\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item mb-5\">\r\n");
      out.write("                <a class=\"nav-link  text-center\" href=\"#\">\r\n");
      out.write("                  자유게시판\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link  text-center\" href=\"");
      out.print( request.getContextPath() );
      out.write("/qaBoard/QnA_Main.jsp\">\r\n");
      out.write("                  QnA\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t        ");
 if(loginMember != null && loginMember.getMemberId().equals("admin")){ 
      out.write("\r\n");
      out.write("\t\t       \t<li class=\"nav-item\">\r\n");
      out.write("\t                <a class=\"nav-link text-center\" \r\n");
      out.write("\t                href=\"");
      out.print(request.getContextPath());
      out.write("/Management/management_Main\">\r\n");
      out.write("\t               \t\t  관리자페이지\r\n");
      out.write("\t                </a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("\t        ");
 } 
      out.write("        \r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("    \t<div class=\"container-fluid pl-5 pr-5 pb-3\" style=\"min-height: 89.3vh;\">\r\n");
      out.write("        <div class=\"row card bg-light\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"container-fluid mt-3\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <h3>Q & A</h3>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row card\">\r\n");
      out.write("                    <div class=\"col-md-12 card-body p-2 aa\" style=\"cursor: pointer;\">\r\n");
      out.write("                        <p class=\"mb-0\">Q. 질문</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 bg-white\" id=\"bb\" style=\"display: none;\">\r\n");
      out.write("                        <p class=\"mb-0\">내용</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row card\">\r\n");
      out.write("                    <div class=\"col-md-12 card-body p-2 aa\" style=\"cursor: pointer;\">\r\n");
      out.write("                        <p class=\"mb-0\">Q. 질문</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 bg-white\" id=\"bb\" style=\"display: none;\">\r\n");
      out.write("                        <p class=\"mb-0\">내용</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"text-center\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary btn-lg m-3\" data-toggle=\"modal\" data-target=\"#exampleModal\">1:1 문의</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("                  <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                      <h5 class=\"modal-title\" id=\"exampleModalLabel\">1:1문의 작성</h5>\r\n");
      out.write("                      <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                      </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        \r\n");
      out.write("                        <form>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <label for=\"recipient-name\" class=\"col-form-label\">제목</label>\r\n");
      out.write("                              <input type=\"text\" class=\"form-control\" id=\"recipient-name\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <label for=\"message-text\" class=\"col-form-label\">내용</label>\r\n");
      out.write("                              <textarea class=\"form-control\" id=\"message-text\"></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-footer\">\r\n");
      out.write("                      <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("                      <button type=\"button\" class=\"btn btn-primary\">작성</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<button class=\"btn btn-secondary dropdown-toggle btn-sm bg-transparent fixed-top\" type=\"button\"\r\n");
      out.write("        id=\"dropdownMenuButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("        <img src=\"");
      out.print( request.getContextPath() );
      out.write("/img/alert3.png\" width=\"42\">\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"dropdownMenuButton\" id=\"dropdown-menu\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dropdown-item  text-center\">\r\n");
      out.write("          <h6 class=\"alertOFF\"> 알람설정 수정하기\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("              <!-- 톱니바퀴 이미지 누를 시 알람설정 페이지로 이동 -->\r\n");
      out.write("              <img src=\"");
      out.print( request.getContextPath() );
      out.write("/img/alarmoff.png\" width=\"30\" height=\"30\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </h6>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 게시글 이름 누를 시 해당 게시글로 이동 -->\r\n");
      out.write("        <h6 class=\"dropdown-header\"> 댓글 알림</h6>\r\n");
      out.write("        <a href=\"#\"><b>&lt;강아지를 잃어버렸습니다&gt;</b></a>게시글에 댓글이 달렸습니다.<br>\r\n");
      out.write("        <a href=\"#\"><b>&lt;강아지를 잃어버렸습니다&gt;</b></a>게시글에 댓글이 달렸습니다.<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- 게시판에 해당 필터링 적용한 목록으로 이동? -->\r\n");
      out.write("        <h6 class=\"dropdown-header\"> 실시간 알림</h6>\r\n");
      out.write("        <mark>찾아주세요</mark><a href=\"#\"><b>&lt;종로구&gt;</b></a>지역에 새로운 게시글이 있습니다.<br>\r\n");
      out.write("        <mark>봤어요</mark><a href=\"#\"><b>&lt;종로구&gt;</b></a>지역에 새로운 게시글이 있습니다.<br>\r\n");
      out.write("        <mark>봤어요</mark><a href=\"#\"><b>&lt;말티즈&gt;</b></a>품종의 새로운 게시글이 있습니다.<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h6 class=\"dropdown-header\"> 1:1문의 답변 알림</h6>\r\n");
      out.write("        <a href=\"#\"><b>&lt;건의사항&gt;</b></a>문의사항에 답변이 달렸습니다.<br>\r\n");
      out.write("        <a href=\"#\"><b>&lt;홈페이지 알람기능 문의&gt;</b></a>문의사항에 답변이 달렸습니다.<br>\r\n");
      out.write("        <a href=\"#\"><b>&lt;미씽펫&gt;</b></a>문의사항에 답변이 달렸습니다.<br>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <title> 미씽펫 방문을 환영합니다! </title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("    integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("    crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css\">\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("    integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\" \r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    <footer id=\"footer\" class=\"\">\r\n");
      out.write("          <div class=\"footer mt-4\">\r\n");
      out.write("            <div class=\"footer text-center \" id=\"footer1\">\r\n");
      out.write("              <span class=\"text-muted\">\r\n");
      out.write("                <b class=\"small\"> | 상호명 : 청포도 | 대표 : 청포도 | 주소 : 서울특별시 광진구 자양로 54 2층 | 사업자 등록번호 : 206-87-05773 | Tel :\r\n");
      out.write("                  010-0000-0000 <br>\r\n");
      out.write("                  Copyright © 2019-2020 Muscat All rights Reserved.\r\n");
      out.write("                </b>\r\n");
      out.write("              </span>\r\n");
      out.write("\r\n");
      out.write("              <span class=\"footer mr-5 small \" id=\"footer2\">\r\n");
      out.write("                <a href=\"#\">이용약관 </a> &nbsp;\r\n");
      out.write("                <a href=\"#\">개인정보처리방침</a>\r\n");
      out.write("              </span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("    integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("    integrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    $(\".aa\").click(function(){\r\n");
      out.write("        if($(this).parent().next(\"div\").children().css(\"display\") == \"none\"){\r\n");
      out.write("            $(this).parent().next(\"div\").children().slideDown();\r\n");
      out.write("        } else{\r\n");
      out.write("            $(this).parent().next(\"div\").children().slideUp();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
