----------------------------------------------------
------------- ATTACHMENT ฐüทร   --------------   
----------------------------------------------------
DROP TABLE ATTACHMENT;

CREATE TABLE ATTACHMENT (
  FILE_NO NUMBER PRIMARY KEY,
  BOARD_ID NUMBER REFERENCES BOARD NOT NULL,
  FILE_ORIGIN_NAME VARCHAR2(255) NOT NULL,
  FILE_CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  FILE_UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  FILE_DOWNLOAD_COUNT NUMBER DEFAULT 0,
  FILE_STATUS CHAR(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_FID;