--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-06-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "MEMBER"."BOOK" 
   (	"BOOK_NO" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"AUTHOR" VARCHAR2(30 BYTE), 
	"SUMMARY" VARCHAR2(400 BYTE), 
	"PRICE" NUMBER, 
	"CONTENT" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MEMBER.BOOK
SET DEFINE OFF;
Insert into MEMBER.BOOK (BOOK_NO,TITLE,AUTHOR,SUMMARY,PRICE,CONTENT) values (1,'제목1','작가1','설명1',5000,'내용1');
Insert into MEMBER.BOOK (BOOK_NO,TITLE,AUTHOR,SUMMARY,PRICE,CONTENT) values (2,'제목2','작가2','설명2',6000,'내용2');
Insert into MEMBER.BOOK (BOOK_NO,TITLE,AUTHOR,SUMMARY,PRICE,CONTENT) values (3,'제목3','작가3','설명3',7000,'내용3');
--------------------------------------------------------
--  DDL for Index SYS_C007364
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEMBER"."SYS_C007364" ON "MEMBER"."BOOK" ("BOOK_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "MEMBER"."BOOK" ADD PRIMARY KEY ("BOOK_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MEMBER"."BOOK" MODIFY ("TITLE" NOT NULL ENABLE);
