INSERT INTO BOARD_TYPE VALUES(10, '찾아요');
INSERT INTO BOARD_TYPE VALUES(20, '봤어요');
INSERT INTO BOARD_TYPE VALUES(30, '분양합니다');
INSERT INTO BOARD_TYPE VALUES(40, '만남그후');
INSERT INTO BOARD_TYPE VALUES(50, '자유게시판');

ALTER TABLE BOARD MODIFY BOARD_STATUS DEFAULT 'N';

SELECT COUNT(*) FROM BOARD WHERE BOARD_STATUS = 'N' AND MEM_ID = ?

INSERT INTO BOARD_TYPE VALUES(1, 'FIND');
INSERT INTO BOARD_TYPE VALUES(2, 'SEE');
INSERT INTO BOARD_TYPE VALUES(3, 'ADOPT');
INSERT INTO BOARD_TYPE VALUES(4, 'REVIEW');
INSERT INTO BOARD_TYPE VALUES(5, 'FREE');



INSERT INTO BOARD VALUES (1, '게시글1', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 1);
INSERT INTO BOARD VALUES (2, '게시글2', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 2);
INSERT INTO BOARD VALUES (3, '게시글3', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 3);
INSERT INTO BOARD VALUES (4, '게시글4', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 4);
INSERT INTO BOARD VALUES (5, '게시글5', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 1);
INSERT INTO BOARD VALUES (6, '게시글6', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 5);
INSERT INTO BOARD VALUES (7, '게시글7', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 2);
INSERT INTO BOARD VALUES (8, '게시글8', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 4);
INSERT INTO BOARD VALUES (9, '게시글9', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 4);
INSERT INTO BOARD VALUES (10, '게시글10', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 2);
INSERT INTO BOARD VALUES (11, '게시글11', '게시글1 내용', DEFAULT, DEFAULT,  DEFAULT,  DEFAULT, DEFAULT, 'user01', 2);

SELECT  BOARD_NO, BOARD_CODE, BOARD_TITLE, BOARD_MODIFY_DT FROM BOARD WHERE BOARD_STATUS = 'N' AND MEM_ID = 'user01' ORDER BY BOARD_NO DESC;


SELECT RNUM, BOARD_NO, BOARD_CODE, BOARD_TITLE, BOARD_MODIFY_DT FROM ( SELECT ROWNUM RNUM, BOARD_NO, BOARD_CODE, BOARD_TITLE, BOARD_MODIFY_DT FROM BOARD WHERE BOARD_STATUS = 'N' AND MEM_ID = 'user01' ORDER BY BOARD_NO DESC) WHERE RNUM BETWEEN 2 AND 4;
            

SELECT COUNT(*) FROM BOARD WHERE BOARD_STATUS = 'N' AND MEM_ID = 'user01';

commit;

INSERT INTO M_COMMENT VALUES(1, '게시글 1의 댓글 1', DEFAULT, DEFAULT, DEFAULT, 'user01', 1);
INSERT INTO M_COMMENT VALUES(2, '게시글 1의 댓글 2', DEFAULT, DEFAULT, DEFAULT, 'user01', 1);
INSERT INTO M_COMMENT VALUES(3, '게시글 1의 댓글 3', DEFAULT, DEFAULT, DEFAULT, 'user01', 1);
INSERT INTO M_COMMENT VALUES(4, '게시글 2의 댓글 1', DEFAULT, DEFAULT, DEFAULT, 'user01', 2);
INSERT INTO M_COMMENT VALUES(5, '게시글 2의 댓글 2', DEFAULT, DEFAULT, DEFAULT, 'user01', 2);
INSERT INTO M_COMMENT VALUES(6, '게시글 3의 댓글 1', DEFAULT, DEFAULT, DEFAULT, 'user01', 3);
INSERT INTO M_COMMENT VALUES(7, '게시글 3의 댓글 2', DEFAULT, DEFAULT, DEFAULT, 'user01', 3);
INSERT INTO M_COMMENT VALUES(8, '게시글 3의 댓글 3', DEFAULT, DEFAULT, DEFAULT, 'user01', 3);
INSERT INTO M_COMMENT VALUES(9, '게시글 3의 댓글 4', DEFAULT, DEFAULT, DEFAULT, 'user01', 3);
INSERT INTO M_COMMENT VALUES(10, '게시글 1의 댓글 4', DEFAULT, DEFAULT, DEFAULT, 'user01', 1);
INSERT INTO M_COMMENT VALUES(11, '게시글 2의 댓글 3', DEFAULT, DEFAULT, DEFAULT, 'user01', 2);
INSERT INTO M_COMMENT VALUES(12, '게시글 3의 댓글 5', DEFAULT, DEFAULT, DEFAULT, 'user01', 3);
INSERT INTO M_COMMENT VALUES(13, '게시글 1의 댓글 5', DEFAULT, DEFAULT, DEFAULT, 'user01', 1);
INSERT INTO M_COMMENT VALUES(14, '게시글 1의 댓글 6', DEFAULT, DEFAULT, DEFAULT, 'user01', 1);
INSERT INTO M_COMMENT VALUES(15, '게시글 6의 댓글 6', DEFAULT, DEFAULT, DEFAULT, 'user01', 6);


commit;

-- 게시판 코드, 게시글 제목, 댓글 내용, 댓글 작성일 -> 댓글 작성 순으로
SELECT  RNUM, BOARD_CODE, BOARD_TITLE, COMM_CONTENT, COMM_MODIFY_DT
FROM (SELECT ROWNUM RNUM, BOARD_NO, BOARD_CODE, BOARD_TITLE, COMM_CONTENT, COMM_MODIFY_DT
            FROM M_COMMENT
            JOIN BOARD USING (BOARD_NO)
            WHERE COMM_STATUS = 'N'
            AND BOARD_STATUS = 'N'
            AND M_COMMENT.MEM_ID = 'user01'
            ORDER BY COMM_NO DESC)
WHERE RNUM BETWEEN 1 AND 5;


SELECT COUNT(*) FROM M_COMMENT
JOIN BOARD USING (BOARD_NO)
WHERE COMM_STATUS = 'N' AND MEM_ID = 'user01'
AND BOARD_STATUS = 'N';


SELECT * FROM M_COMMENT
JOIN BOARD USING (BOARD_NO)
WHERE MEM_ID = 'user02';

ALTER TABLE M_COMMENT
RENAME COLUMN MEMBER_ID TO MEM_ID;




